AWSTemplateFormatVersion: '2010-09-09'
Description: 'Automated Helpdesk PoC - IAM Roles and Policies'

Parameters:
  Environment:
    Type: String
    Description: 'Deployment environment'
  
  StackName:
    Type: String
    Description: 'Parent stack name'

Conditions:
  IsProduction: !Equals [!Ref Environment, 'production']

Resources:
  # Lambda実行ロール
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'helpdesk-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:Retrieve
                  - bedrock:RetrieveAndGenerate
                Resource: 
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
                  - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:knowledge-base/*'
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::helpdesk-knowledge-${Environment}'
                  - !Sub 'arn:aws:s3:::helpdesk-knowledge-${Environment}/*'

  # Bedrock Knowledge Base用ロール
  BedrockKnowledgeBaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'helpdesk-bedrock-kb-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::helpdesk-knowledge-${Environment}'
                  - !Sub 'arn:aws:s3:::helpdesk-knowledge-${Environment}/*'

  # Amazon Connect用ロール
  ConnectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'helpdesk-connect-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: connect.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: LambdaInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:automated-helpdesk-processor-${Environment}'

Outputs:
  LambdaExecutionRoleArn:
    Description: 'Lambda Execution Role ARN'
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${StackName}-LambdaExecutionRoleArn'
  
  BedrockKnowledgeBaseRoleArn:
    Description: 'Bedrock Knowledge Base Role ARN'
    Value: !GetAtt BedrockKnowledgeBaseRole.Arn
    Export:
      Name: !Sub '${StackName}-BedrockKnowledgeBaseRoleArn'
  
  ConnectRoleArn:
    Description: 'Connect Role ARN'
    Value: !GetAtt ConnectRole.Arn
    Export:
      Name: !Sub '${StackName}-ConnectRoleArn'