AWSTemplateFormatVersion: '2010-09-09'
Description: 'Automated Helpdesk PoC - Storage Resources (S3)'

Parameters:
  Environment:
    Type: String
    Description: 'Deployment environment'
  
  StackName:
    Type: String
    Description: 'Parent stack name'

Resources:
  # ナレッジベース用S3バケット
  KnowledgeBaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'helpdesk-knowledge-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3600

  # CloudFormationアーティファクト用S3バケット（既存の場合はスキップ）
  # 注：deploy.shスクリプトで既に作成されているため、ここではコメントアウト
  # ArtifactsBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub 'helpdesk-cfn-artifacts-${Environment}-${AWS::Region}'
  #     BucketEncryption:
  #       ServerSideEncryptionConfiguration:
  #         - ServerSideEncryptionByDefault:
  #             SSEAlgorithm: AES256
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: true
  #       BlockPublicPolicy: true
  #       IgnorePublicAcls: true
  #       RestrictPublicBuckets: true
  #     VersioningConfiguration:
  #       Status: Enabled
  #     LifecycleConfiguration:
  #       Rules:
  #         - Id: DeleteOldArtifacts
  #           Status: Enabled
  #           ExpirationInDays: 30

Outputs:
  KnowledgeBaseBucketName:
    Description: 'S3 Bucket Name for Knowledge Base'
    Value: !Ref KnowledgeBaseBucket
    Export:
      Name: !Sub '${StackName}-KnowledgeBaseBucketName'
  
  KnowledgeBaseBucketArn:
    Description: 'S3 Bucket ARN for Knowledge Base'
    Value: !GetAtt KnowledgeBaseBucket.Arn
    Export:
      Name: !Sub '${StackName}-KnowledgeBaseBucketArn'
